version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    ports:
      - "80:8080"
      - "443:8443"
      - "8001:8001"
networks:
  envoymesh: {}
